name: Create Release on Push to Release Branch

on:
  push:
    branches:
      - release
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Merge to Release"
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install deps
        run: |
          pacman -Sy --needed --noconfirm git base-devel

      - name: Debug
        run: |
          ls -la
          whoami
          pwd

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build user
        run: |
          useradd -m cilgin
          echo 'cilgin ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

      - name: Change permissions
        run: |
          mkdir localrepo
          chown -R cilgin:cilgin .


      # - name: Build PKGBUILD
      #   run: |
      #     cd localrepo
      #     ls -la
      #     ls -la ..
      #     ../update.sh


      - name: Install archiso
        run: |
          pacman -Sy --needed --noconfirm archiso


      - name: Install Zsh
        run: |
          pacman -Sy --needed --noconfirm zsh

      - name: Zinit files
        run: |
          cp releng/airootfs/etc/skel/.zshrc $HOME
          export TERM=xterm
          zsh -c "source ~/.zshrc"
          find $HOME/.local/share/zinit -type d -name ".git" -print -exec rm -rf {} +
          cp -r $HOME/.local/share/zinit/ ./releng/airootfs/home/cilgin/.local/share/

      - name: Install nvim
        run: |
          pacman -Sy --needed --noconfirm nvim

      - name: Install nvchad
        run: |
          git clone --depth 1 https://github.com/NvChad/starter $HOME/.config/nvim
          git clone --depth 1 https://github.com/NvChad/starter ./releng/airootfs/home/cilgin/.config/nvim
          nvim --headless '+Lazy! sync' +qa
          find $HOME/.local/share/nvim -type d -name ".git" -print -exec rm -rf {} +
          cp -r $HOME/.local/share/nvim/ ./releng/airootfs/home/cilgin/.local/


      - name: Clean up and Build ISO
        run: |
          chown -R root:root .
          find ./releng/airootfs -type d -name ".git" -print -exec rm -rf {} +
          
          if [ -n "$(find ./releng/airootfs -type d -name '.git')" ]; then
            find ./releng/airootfs -type d -name ".git"
            exit 1
          else
            echo "Cleanup successful."
          fi


      - name: Build ISO
        run: |
          mkdir out
          mkdir output
          ls -la
          ls -la out
          ls -la output
          mkarchiso -v -w ./output -o ./out releng || true
          cd output
          ls -la
          find . -type d -name ".git" -print -exec rm -rf {} +
          mkarchiso -v -w ./output -o ./out releng


      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./out/*
          tag_name: release-${{ steps.vars.outputs.sha_short }}
          name: "Release - Commit ${{ steps.vars.outputs.sha_short }}"
          body: "Automated release from push to release branch."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
