name: Create Release on Push to Release Branch

on:
  push:
    branches:
      - release
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Push to Release"
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install deps
        run: |
          pacman -Sy --needed --noconfirm git base-devel

      - name: Debug
        run: |
          ls -la
          whoami
          pwd

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug
        run: |
          ls -la
          pwd

      - name: Create build user
        run: |
          useradd -m builder

      - name: Change permissions
        run: |
          chown -R builder:builder /__w/cilginOS/cilginOS/ 
          su builder

      - name: Build PKGBUILD
        run: |
          mkdir localrepo
          cd localrepo
          ../update.sh

      - name: Debug
        run: |
          ls -la
          pwd

      - name: Install archiso
        run: |
          pacman -Sy --needed --noconfirm archiso

      - name: Debug
        run: |
          ls -la
          pwd

      - name: Build ISO
        run: |
          mkarchiso -v -w /__w/cilginOS/cilginOS/output releng

      - name: Debug
        run: |
          ls -la
          ls -la out
          ls -la output
          pwd

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./out/*
          tag_name: release-${{ steps.vars.outputs.sha_short }}
          name: "Release - Commit ${{ steps.vars.outputs.sha_short }}"
          body: "Automated release from push to release branch."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
