name: Merge to Release

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 1 * *"


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge main to release
        run: |
          echo "🔄 Merge main to release branch"
          git checkout release
          git merge main
          git push origin release

      - name: ✅ Done
        run: |
          echo "🎉 Release branch updated!"
          echo "🕒 Time: $(date)"
